version: "3.9"

services:

  web:
    build: ./Client # Dockerfile location to current path
    ports:
      - 8080:80
    depends_on:
      - api

  api:
    build: ./Api # Dockerfile location to current path
    ports:
      - 8081:80
    environment:
      POSTGRESQL_CONNECTION_STRING: "Server=db;Port=5432;Database=neven;User Id=neven;Password=Passw0rd;"
    depends_on:
      - db

  db:
    image: postgres:alpine3.15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=neven
      - POSTGRES_PASSWORD=Passw0rd
      #   volumes:
      #     - myvolume:/data/db #check this path for postrgresql db "/data/db"

      # volumes:
      #   myvolume: #we just define empty volume before we can use it

      # docker-compose build --no-cache (in the same folder as docker-compose.yml file)
      # docker-compose up
      # docker-compose down
      # docker-compose logs
